abc: 
  image:
    repository: odaprdacr.azurecr.io/abc
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.1.0"
    tagSuffix: "-release"
def: 
  image:
    repository: odaprdacr.azurecr.io/def
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.2.0"
    tagSuffix: "-release"
ghi: 
  image:
    repository: odaprdacr.azurecr.io/ghi
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.3.0"
    tagSuffix: "-release"
